# MARIAN PCIe soundcards ALSA driver
#
# Author: Tobias Groß <theguy@audio-fpga.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details at:
# http://www.gnu.org/licenses/gpl-2.0.html

snd-marian-objs := marian.o device_abstraction.o device_generic.o clara.o \
	clara_e.o clara_emin.o dma_ng.o
obj-m += snd-marian.o
